hmcts/et-pet-ccd-export

.gitignore, Gemfile, Gemfile.lock, app/services/et_ccd_export/export_claim_service.rb, spec/factories/export_factory.rb
This PR extracts the ccd client code into its own gem so the full system test suite can read from CCD
=> Switched to using ccd client gem

azure-pipelines.yml
=> Implementing Azure Devops pipeline

Gemfile, Gemfile.lock, README.md, app/services/export_claim_service.rb, app/workers/et_exporter/export_claim_worker.rb, config/initializers/ccd_client.rb, spec/factories/address_factory.rb, spec/factories/claim_factory.rb, spec/factories/claimant_factory.rb, spec/factories/representative_factory.rb, spec/factories/respondent_factory.rb, spec/factories/system_factory.rb, spec/factories/uploaded_file_factory.rb, spec/integration/create_claim_spec.rb, spec/json_schemas/case_create.json, spec/services/export_claim_service_spec.rb, spec/support/ccd_client.rb, spec/support/json_matchers.rb, spec/support/sidekiq.rb, spec/support/webmock.rb
This PR adds create case functionality - working with ccd-docker but not with a real system yet, which is assumed to be configuration issues 
https://tools.hmcts.net/jira/browse/RST-1933
This PR adds create case functionality - working with ccd-docker but not with a real system yet, which is assumed to be configuration issues 
```
[ ] Yes
[X] No
```
=> Rst 1933 ccd case create

Gemfile, Gemfile.lock
N/A
Upgraded ccd client to 0.1.29 to improve error handling and logging
```
[ ] Yes
[X] No
```
=> Upgraded ccd client to 0.1.29 to improve error handling and logging

Gemfile, Gemfile.lock, lib/ccd_client_sentry_error_middleware.rb
N/A
Error handling should now include the request that caused the error
```
[ ] Yes
[X] No
```
=> Error handling should now include the request that caused the error

azure-pipelines.yml
=> Fix to ADO docker task change

Gemfile, Gemfile.lock, config/initializers/ccd_client.rb, spec/support/ccd_client.rb
N/A
Upgraded client - will improve error reporting and logging
```
[ ] Yes
[X] No
```
=> Upgraded client - will improve error reporting and logging

app/views/export_claim_service/top.json.jbuilder, app/views/export_multiple_claims_service/lead_claimant_data.json.jbuilder, app/views/export_multiple_claims_service/secondary_claimant_data.json.jbuilder, spec/json_schemas/case_create.json
RST-2102
Added positionType field as requested by ethos replacement team
```
[ ] Yes
[X] No
```
=> RST-2102 (CCD) - positionType

app/services/concerns/async_application_events.rb, app/services/export_claim_service.rb, app/services/export_multiple_claims_service.rb, app/workers/et_exporter/export_claim_worker.rb, app/workers/export_multiples_header_worker.rb, app/workers/export_multiples_worker.rb, spec/factories/export_factory.rb, spec/factories/system_factory.rb, spec/integration/create_claim_multiples_spec.rb, spec/integration/create_claim_spec.rb, spec/services/export_multiple_claims_service_spec.rb, spec/support/drain_all_our_sidekiq_jobs.rb, spec/support/external_events.rb, spec/support/shared_contexts/with_mock_api_event_worker.rb, spec/support/sidekiq.rb, spec/workers/export_multiples_worker_spec.rb
RST-2197
This PR introduces positive feedback only for claims  using events fired over sidekiq to keep the app loosely coupled
```
[ ] Yes
[X] No
```
=> Rst 2197 export states

app/workers/export_multiples_worker.rb, lib/ccd_client_sentry_error_middleware.rb
RST-2215
Bug fix - during exception reporting
```
[ ] Yes
[X] No
```
=> RST-2215 (CCD, ADMIN, API) - Bug fix - during exception reporting

app/services/export_multiple_claims_service.rb
RST-2262
Fix issue where batch error recovery did not ever complete the batch on retry
```
[ ] Yes
[X] No
```
=> RST-2262 (CCD) - Batch error recovery for multiples not working

azure-pipelines.yml
adding no test build image job
```
[ ] Yes
[x] No
```
=> adding no test build image job

app/views/export_multiple_claims_service/header.json.jbuilder, spec/presenters/multiple_claims_header_presenter_spec.rb
=> RST-2498 Populate case source

app/services/concerns/claim_files.rb, spec/factories/claim_factory.rb, spec/factories/uploaded_file_factory.rb, spec/integration/create_claim_multiples_spec.rb, spec/integration/create_claim_spec.rb, spec/support/ccd_client.rb
RST-2382
Adds functionality to receive acas files from API
```
[ ] Yes
[X] No
```
=> Rst 2382 acas

Gemfile, Gemfile.lock, config/application.rb, config/environments/development.rb, config/environments/test.rb
RST-2144
This PR implements app insights
```
[ ] Yes
[X] No
```
=> Rst 2144 insights

app/workers/export_multiples_header_worker.rb, spec/workers/export_multiples_header_worker_spec.rb
https://tools.hmcts.net/jira/browse/RST-2520
This PR fixes the issue when retries are exhausted and the claim cannot be exported
```
[ ] Yes
[X] No
```
=> RST-2520 (CCD) Bug in export_multiples:header_worker.rb

app/views/export_claim_service/top.json.jbuilder, app/views/export_multiple_claims_service/lead_claimant_data.json.jbuilder, app/views/export_multiple_claims_service/secondary_claimant_data.json.jbuilder, spec/json_schemas/case_create.json
https://tools.hmcts.net/jira/browse/RST-2710
This PR changes the positionType field to 'Received by Auto-Import' as requested by the ECM team
```
[X] Yes
[ ] No
```
=> RST-2710 (CCD) Change positionType to 'Received by Auto-Import'

Gemfile, Gemfile.lock
=> RST-2778 (CCD) Cases erroring with 401 regularly in production

app/views/export_multiple_claims_service/lead_claimant_data.json.jbuilder, app/views/export_multiple_claims_service/secondary_claimant_data.json.jbuilder, spec/json_schemas/case_create.json
https://tools.hmcts.net/jira/browse/RST-2879
Adds new lead claimant field to payload
```
[ ] Yes
[ ] No
```
=> RST-2879 Add new lead claimant field and deprecate leadClaimant1

app/views/export_multiple_claims_service/lead_claimant_data.json.jbuilder, app/views/export_multiple_claims_service/secondary_claimant_data.json.jbuilder, spec/integration/create_claim_multiples_spec.rb, spec/json_schemas/case_create.json
https://tools.hmcts.net/jira/browse/RST-2976
Removed leadClaimant1 from the payload
```
[ ] Yes
[ ] No
```
=> RST-2976 Removed leadClaimant1 field

azure-pipelines.yml
=> Update pool for build and push tasks

README.md, app/workers/export_multiples_header_worker.rb, config/environments/production.rb
=> RST-3278 (CCD) Improved logging for diagnostics

README.md, app/exceptions/claim_multiple_claimant_count_exceeded_exception.rb, app/services/application_events_service.rb, app/services/export_multiple_claims_service.rb, app/workers/et_exporter/export_claim_worker.rb, spec/factories/export_factory.rb, spec/factories/system_factory.rb, spec/integration/create_claim_multiples_spec.rb, spec/support/external_events.rb
This PR allows multiple claim size to be restricted on an office by office basis for ECM
```
[ ] Yes
[X] No
```
=> RST-3253 Limit on multiple claimants

Dockerfile.dev, config/application.rb, config/environments/development.rb, config/initializers/sidekiq.rb, config/sidekiq.yml
RST-4439
```
[ ] Yes
[X] No
```
=> Changes for use with scaffold

app/services/concerns/claim_files.rb, spec/integration/create_claim_multiples_spec.rb, spec/json_schemas/case_create.json
=> (RST-5263) Changed document type for et1 attachments

app/services/concerns/claim_files.rb, spec/integration/create_claim_multiples_spec.rb, spec/json_schemas/case_create.json
This reverts commit 919f0d43466b7027144cbd8b4b3422b807252af1.
```
[ ] Yes
[ ] No
```
=> Revert "(RST-5263) Changed document type for et1 attachments (#316)"

app/services/concerns/claim_files.rb, app/services/concerns/response_files.rb
This PR allows the converted pdf files created by the API to be exported to CCD
```
[X] Yes
[ ] No
```
=> (RST-5149) Allowing for new pdf files (were rtf) to be sent to ccd

lib/ccd_client_sentry_error_middleware.rb
=> (RST-5651) Bug fix in application when errors occur

charts/et-pet-ccd-export/Chart.yaml, charts/et-pet-ccd-export/values.yaml, config/initializers/sidekiq.rb
=> (RST-5651) Enabling SSL for redis

charts/et-pet-ccd-export/Chart.yaml, charts/et-pet-ccd-export/values.yaml
=> (RST-5651) Fixed CCD URLs with templating

charts/et-pet-ccd-export/Chart.yaml, charts/et-pet-ccd-export/values.yaml
=> (RST-5651) Corrected ingress url to internal

charts/et-pet-ccd-export/Chart.yaml, charts/et-pet-ccd-export/values.yaml
=> (RST-5651) Fixed docmosis url

spec/rails_helper.rb
=> (RST-5959) Fixed coverage

spec/json_schemas/case_create.json
=> (RST-5628) case_create.json - removed required date of birth

charts/et-pet-ccd-export/Chart.yaml, charts/et-pet-ccd-export/values.yaml
=> (RST-5976) Switch to using new app insights

Gemfile.lock
=> (RST-6289) Upgraded nokogiri (security issue)

Gemfile.lock, charts/et-pet-ccd-export/Chart.yaml
=> (RST-6542) Updated rotp gem due to vulnerability

app/helpers/title_helper.rb, app/views/export_claim_service/top.json.jbuilder, app/views/export_multiple_claims_service/lead_claimant_data.json.jbuilder, app/views/export_multiple_claims_service/secondary_claimant_data.json.jbuilder, spec/integration/create_claim_spec.rb, spec/json_schemas/case_create.json
=> (RST-6745) Claimant other title field now sent to ccd

Gemfile.lock, charts/et-pet-ccd-export/Chart.yaml
https://tools.hmcts.net/jira/browse/RST-7191
=> RST-7191 - Helm update
